[plugins.telesync] auto-restrict new users
das7pad/hangoutsbot pull request #9
Opened 2017-09-10 11:32 UTC by deffnull

- can be controlled with per conversation config key “sync_restrict_user”, default off

2017-09-10 13:01 UTC, das7pad requested changes
Great idea to add another mod function to `telesync`!

There is a lot of duplicate code here: what about splitting `plugins.telesync.commands_tg.command_restrict_user` into a core and command head:
- the head would enforce an admin user and `args`/valid option and sends the result back
- the core is feed with the `restrict` mode and `args` to parse the specified user_ids; it could simply return the `failed` dict.

We could use the restrict_user core then to run it with the user ids of the changed member.

2017-09-10 13:01 UTC, das7pad commented on hangupsbot/sync/__init__.py
> +    'sync_restrict_user': '',
Let's keep the telesync defaults in `plugins.telesync.setup_config.default_config` and access them with `bot.get_config_suboption`.

2017-09-10 13:01 UTC, das7pad commented on hangupsbot/plugins/telesync/core.py
> +                    result = await self.restrictChatMember(msg.chat_id,
We are actually not in a coroutine here, this requires `async def _on_membership_change(...):` and `await self._on_membership_change(msg)` in line 485.

2017-09-10 13:01 UTC, das7pad commented on hangupsbot/plugins/telesync/core.py
> +                        mod_chat = self.config('mod_chat') if 'mod_chat' in self.config() else None
What about an entry in `plugins.telesync.setup_config.default_config` for `mod_chat`?

2017-09-10 13:01 UTC, das7pad commented on hangupsbot/plugins/telesync/core.py
> +                    result = await self.restrictChatMember(msg.chat_id,
`TelegramBot.restrictChatMember` likely raises an Exception - the membership change would never reach the sync handler in this case.

2017-09-13 12:09 UTC, das7pad commented
> what about splitting plugins.telesync.commands_tg.command_restrict_user into a core and command head

done in https://github.com/das7pad/hangoutsbot/commit/71b6ca0d7e2eb7d8af25c4223773a0936eb16677

2017-11-12 19:39 UTC, deffnull commented
Changes applied based on 71b6ca0

2017-11-12 21:52 UTC, merged

2017-11-12 21:52 UTC, das7pad commented
Thank you!